# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Map',                url: 'map'}
- {name: 'About',              url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fa-instagram', link:  'https://instagram.com/alperkal'}
- {icon: 'fa-linkedin', link:  'https://www.linkedin.com/in/alperkal'}
- {icon: 'fa-strava', link:  'https://www.strava.com/athletes/2824298'}
- {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
